FROM node:lts-alpine AS build-deps
WORKDIR /usr/src/app
COPY package.json ./
RUN npm install
COPY . ./
RUN npm run build

FROM nginx:alpine
COPY ./deploy/nginx.dev.conf /etc/nginx/nginx.conf
COPY --from=build-deps /usr/src/app/dist /usr/share/nginx/html
RUN apk add apache2-utils
RUN mkdir etc/apache2 && touch etc/apache2/.htpasswd
RUN htpasswd -b /etc/apache2/.htpasswd admin ${NGINX_ADMIN_AUTH:-toto}
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
